config/routes.rb
RedditClone::Application.routes.draw do
  root to: "users#index"

  resources :users
  resource :session, only: [:create, :new, :destroy]

  resources :subs do
    resources :posts do
      get "xpost/new", to: "posts#xpost_new", as: "new_xpost"
      post "xpost", to: "posts#xpost", as: "xpost"

      resources :comments
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_reader :password

  validates :name, :password_digest, :session_token, :activation_token, presence: true
  validates :name, :session_token, :activation_token, uniqueness: true

  validates :activated, inclusion: { in: [true, false] }
  validates :password, length: { minimum: 6 }

  after_initialize :generate_unique_session_token, :generate_unique_activation_token

  has_many :comments,
  class_name: "Comment",
  foreign_key: :author_id,
  primary_key: :id,
  inverse_of: :author

  has_many :subs,
    class_name: "Sub",
    foreign_key: :moderator_id,
    primary_key: :id,
    inverse_of: :moderator

  has_many :posts,
    class_name: "Post",
    foreign_key: :author_id,
    primary_key: :id,
    inverse_of: :author


  def self.find_by_credential(user_params)

    user = User.find_by(name: user_params[:name])
    if user
      return user if user.is_password?(user_params[:password])
    end

    nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    @password = password
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    generate_unique_session_token
    save!
    self.session_token
  end


  private
  def generate_unique_session_token
    begin
      self.session_token = SecureRandom.urlsafe_base64(16)
    end until !self.class.exists?(:session_token => self.session_token)
  end

  def generate_unique_activation_token
    begin
      self.activation_token = SecureRandom.urlsafe_base64(16)
    end until !self.class.exists?(:activation_token => self.activation_token)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to users_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def index
    render :index
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def form_auth
    "<input type='hidden'
           name='authenticity_token'
           value='#{form_authenticity_token}'>".html_safe
  end
end

app/views/users/index.html.erb
Check out all the subs!

<br><br>
<% Sub.all.each do |sub| %>

  <li style="text-indent: 50px"><a href="<%= sub_url(sub) %>" ><%= sub.title %></a></li>

<% end %>

<br><br>
<% if current_user %>
	<a href="<%= new_sub_url %>">Create a new sub!</a>
<% end %>

app/views/users/new.html.erb
<h1>Create new user!</h1>

<form action="<%= users_url %>" method="POST">
  <%= form_auth %>
  <label for="user_name">Username: </label>
  <input type="text" name="user[name]" id="user_name" value="<%= @user.name %>">
  <br>
  <label for="user_email">Email (optional): </label>
  <input type="text" name="user[email]" id="user_email" value="<%= @user.email %>">
  <br>
  <label for="user_password">Password: </label>
  <input type="password" name="user[password]" id="user_password">


  <br><br>
  <input type="submit" value="Create!">

</form>