config/routes.rb
RedditClone::Application.routes.draw do
  root to: "users#index"

  resources :users
  resource :session, only: [:create, :new, :destroy]

  resources :subs do
    resources :posts do
      get "xpost/new", to: "posts#xpost_new", as: "new_xpost"
      post "xpost", to: "posts#xpost", as: "xpost"

      resources :comments
    end
  end

end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :moderator_id, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator,
    class_name: "User",
    foreign_key: :moderator_id,
    primary_key: :id,
    inverse_of: :subs

  has_many :posts, inverse_of: :sub, dependent: :destroy

  has_many :post_subs, inverse_of: :sub

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = current_user.subs.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy
    redirect_to users_url
  end

  def edit
    @sub = Sub.find(params[:id])
    render :new
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/new.html.erb
<% title = @sub.persisted? ? "Edit #{@sub.title}" : "Create new sub" %>
<% submit_thing = @sub.persisted? ? "Edit" : "Create" %>
<% form_method = @sub.persisted? ? "PATCH" : "POST" %>
<% action_url = @sub.persisted? ? sub_url(@sub) : subs_url %>

<h1><%= title %></h1>

<form action="<%= action_url %>" method="POST">
  <%= form_auth %>
  <input type="hidden" name="_method" value="<%= form_method %>">
  <label for="sub_title">Title: </label>
  <br>
  <input type="text" id="sub_title" name="sub[title]" value="<%= @sub.title %>">

  <br><br>
  <label for="sub_description">Description: </label>
  <br>
  <textarea name="sub[description]" id="sub_description"
  ><%= @sub.description %></textarea>
  <br>
  <br>
  <input type="submit" value="<%= submit_thing %>">
</form>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<h4>Description: </h4>

<p style="text-indent: 50px"><%= @sub.description %></p>

<br>

<% sub_posts = @sub.posts %>
<% if sub_posts.empty? %>
  There are no posts yet...
  <br><br>
<% else %>
  <strong>Posts!</strong>
  <ul>
    <% PostSub.all.each do |post_sub| %>

    <% if post_sub.sub_id == @sub.id %>
      <% post = post_sub.post %>

        <li><a href="<%= post.url %>"><%= post.title %></a></li>
        &nbsp&nbsp&nbsp<a href="<%= sub_post_url(sub_id: @sub.id, id: post.id)
         %>">comments</a>

    <% end %>


    <% end  %>
  </ul>
<% end %>

<% if current_user %>
  <a href="<%= new_sub_post_url(sub_id: @sub.id) %>">make new post!</a>
<% end %>

<br>
<a href="<%= users_url %>">back to all subs</a>
<br>
<br>

<% if current_user && (current_user.id == @sub.moderator_id) %>
  <form action="<%= edit_sub_url(@sub) %>" method="GET">
    <%= form_auth %>
    <input type="submit" value="Edit sub">
  </form>

  <form action="<%= sub_url(@sub) %>" method="POST">
    <%= form_auth %>
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Delete sub permanently">
  </form>
<% end %>