config/routes.rb
RedditClone::Application.routes.draw do
  root to: "users#index"

  resources :users
  resource :session, only: [:create, :new, :destroy]

  resources :subs do
    resources :posts do
      get "xpost/new", to: "posts#xpost_new", as: "new_xpost"
      post "xpost", to: "posts#xpost", as: "xpost"

      resources :comments
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :sub, :author, presence: true

  belongs_to :sub, inverse_of: :posts
  belongs_to :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id,
    inverse_of: :posts

  has_many :post_subs, inverse_of: :post, dependent: :destroy

  has_many :comments, inverse_of: :post, dependent: :destroy

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new(sub_id: params[:sub_id])
    render :new
  end

  def create
    @post = current_user.posts.new(post_params)
    url = @post.url

    @post.url = "http://" + url unless (url[0..6] == "http://") || (url[0..7] == "https://")

    if @post.save
      PostSub.create(post_id: @post.id, sub_id: params[:sub_id])
      redirect_to sub_post_url(id: @post.id)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post_sub = PostSub.find_by(post_id: params[:id], sub_id: params[:sub_id])
    @post = Post.find(@post_sub.post_id)

    render :show
  end

  def destroy
    @post_sub = PostSub.find_by(post_id: params[:id], sub_id: params[:sub_id])
    @post_sub.destroy
    redirect_to sub_url(Sub.find(params[:sub_id]))
  end

  def edit
    @post_sub = PostSub.find_by(post_id: params[:id], sub_id: params[:sub_id])
    @post = Post.find(@post_sub.post_id)
    render :new
  end

  def update
    @post_sub = PostSub.find_by(post_id: params[:id], sub_id: params[:sub_id])
    @post = Post.find(@post_sub.post_id)
    if @post.update(post_params)
      redirect_to sub_post_url(id: @post.id)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end


  def xpost_new
    @post = Post.find(params[:post_id])
    render :xpost_new
  end

  def xpost
    sub_id = Sub.find_by_title(params[:x_post][:sub]).id
    @post_sub = PostSub.new(sub_id: sub_id, post_id: params[:post_id])

    if @post_sub.save
      redirect_to sub_post_url(id: params[:post_id], sub_id: sub_id)
    else
      flash.now[:errors] = @post_sub.errors.full_messages
      render :xpost_new
    end

  end

  private
  def post_params
    post_params = params.require(:post).permit(:title, :url, :content)
    post_params.merge(sub_id: params[:sub_id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_loop.html.erb
<% current_comments.each do |current_comment| %>
	<%= "------" * counter %>
	<%= current_comment.author.name%> says:
	<%= current_comment.content %>

	<% indent_val = (35 * counter).to_s %>
  
	<% if params[:reply_id].to_i == current_comment.id %>
	  	<form style="margin:5px 0 0 <%= indent_val %>px;" action="<%= sub_post_comments_url(post_id: params[:id], parent_comment_id: current_comment.id) %>" method="POST">
	 		<%= form_auth %>
	 		<label for="comment_content">Make comment!</label><br>
	 		<textarea name="comment[content]" id="comment_content"></textarea><br>
	 		<input type="submit" value="comment">
	 	</form>
	 <% else %>
	  	<form action="<%= sub_post_url %>" method="GET">
	  		<input type="hidden" name="reply_id" value="<%= current_comment.id %>">
	  		<input style="margin:5px 0 0 <%= indent_val %>px;" type="submit" value="reply">
	  	</form>
	<% end %>
	<br>

	<%= render "comment_loop", current_comments: current_comment.comments, counter: counter + 1 %>
<% end %>

app/views/posts/new.html.erb
<% title = @post.persisted? ? "Edit #{@post.title}" : "Create new post" %>
<% submit_thing = @post.persisted? ? "Edit" : "Create" %>
<% form_method = @post.persisted? ? "PATCH" : "POST" %>
<% action_url = @post.persisted? ? sub_post_url(id: @post.id, sub_id: params[:sub_id])  : sub_posts_url  %>

<h1><%= title %></h1>

<form action="<%= action_url %>" method="POST">
  <%= form_auth %>

  <input type="hidden" name="_method" value="<%= form_method %>">
  <label for="post_title">Title: </label>
  <input type="text" id="post_title" name="post[title]" value="<%= @post.title %>">

  <br>
  <label for="post_url">URL: </label>
  <input type="text" id="post_url" name="post[url]" value="<%= @post.url %>">
  <br>

  <label for="post_content">Content: </label>
  <textarea name="post[content]" id="post_content"
  ><%= @post.content  %></textarea>
  <br>
  <br>

  <input type="submit" value="<%= submit_thing %>">

</form>

<a href="<%= sub_url(params[:sub_id]) %>"
  >Back to <%= Sub.find(params[:sub_id]).title %></a>

app/views/posts/show.html.erb
<h1>URL: <a href="<%= @post.url %>"><%= @post.title %></a></h1>
<h3>Author: <%= @post.author.name %></h3>
content:
<table border="100">
  <tr><td><p><%= @post.content %></p></td></tr>
</table>
<% if current_user %>
<br><br>
<form action="<%= sub_post_comments_url(post_id: params[:id]) %>" method="POST">
 	<%= form_auth %>
 	<label for="comment_content">Make comment!</label><br>
 	<textarea name="comment[content]" id="comment_content"></textarea><br>
 	<input type="submit" value="comment">
 </form>
 <br>
 <% else %>
 <br>
<% end %>

<% current_comments = @post.comments.select {|c| c.parent_comment_id.nil? } %>
<%= render "comment_loop", current_comments: current_comments, counter: 0 %>

<br>
<a href="<%= sub_url(@post.sub) %>">back to all post</a>

<br><br>
<% if current_user && current_user.id == @post.author_id %>
<form action="<%= sub_post_new_xpost_url(sub_id: @post.sub.id, post_id: @post.id) %>" method="GET">
  <input type="submit" value="make crossxpost">
</form>

<form action="<%= edit_sub_post_url(sub_id: @post.sub.id, id: @post.id) %>" method="GET">
  <input type="submit" value="edit post">
</form>

<form action="<%= sub_post_url(sub_id: params[:sub_id], id: params[:id]) %>" method="POST">
  <%= form_auth %>
  <input type="hidden" name="_method" value="DELETE">
  <input type="submit" value="delete post">
</form>
<% end %>

app/views/posts/xpost_new.html.erb
<h1>Make crossxpost</h1>

<h1>URL: <%= @post.title %></h1>
<h3>Author: <%= @post.author.name %></h3>
content:
<table border="100">
  <tr><td><p><%= @post.content %></p></td></tr>
</table>

<br>
<a href="<%= sub_url(@post.sub) %>">back to all post</a>

<br><br>
<% if current_user.id == @post.author_id %>
<form action="<%= sub_post_xpost_url(sub_id: @post.sub.id, post_id: @post.id) %>" method="POST">
  <%= form_auth %>

  <label for="sub_to_xpost">sub to crossxpost to</label>
  <input type="text" id="sub_to_xpost" name="x_post[sub]">
  <input type="submit" value="crossxpost!">
</form>

<% end %>